# Generated by Django 5.1.6 on 2025-03-01 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flashcard', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Flashcard',
        ),
    ]
