# Generated by Django 5.1.6 on 2025-04-13 05:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_jobposting'),
        ('interpreter', '0002_alter_availability_interpreter_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('declined', 'Declined'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('interpreter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='interpreter.interpreter')),
                ('job_posting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='company.jobposting')),
            ],
            options={
                'unique_together': {('job_posting', 'interpreter')},
            },
        ),
    ]
