# Generated by Django 5.1.6 on 2025-03-28 17:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interpreter', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='availability',
            name='interpreter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availability', to='interpreter.interpreter'),
        ),
        migrations.AlterField(
            model_name='interpretercertification',
            name='interpreter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certification', to='interpreter.interpreter'),
        ),
        migrations.AlterField(
            model_name='interpreterlanguage',
            name='interpreter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='language', to='interpreter.interpreter'),
        ),
    ]
