# Generated by Django 5.1.6 on 2025-05-08 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interpreter', '0002_alter_availability_interpreter_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interpreter',
            name='phone_number',
            field=models.BigIntegerField(),
        ),
    ]
