# Generated by Django 5.1.6 on 2025-02-21 10:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz',
            name='answer',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='correct_answer',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='option_1',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='option_2',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='option_3',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='option_4',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='question',
        ),
        migrations.AddField(
            model_name='quiz',
            name='description',
            field=models.TextField(default='hiragana'),
        ),
        migrations.AddField(
            model_name='quiz',
            name='title',
            field=models.CharField(default='hiragana', max_length=200),
        ),
        migrations.AlterField(
            model_name='category',
            name='level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='quiz_app.level'),
        ),
        migrations.AlterField(
            model_name='level',
            name='name',
            field=models.CharField(choices=[('Beginner', 'Beginner'), ('Advanced', 'Advanced')], default='Beginner', max_length=10),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quizzes', to='quiz_app.category'),
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField()),
                ('time_limit', models.IntegerField(default=30)),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='quiz_app.quiz')),
            ],
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_text', models.CharField(max_length=255)),
                ('is_correct', models.BooleanField(default=False)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='quiz_app.question')),
            ],
        ),
    ]
