# Generated by Django 5.1.6 on 2025-02-21 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_app', '0002_remove_quiz_answer_remove_quiz_correct_answer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
