# Generated by Django 5.1.6 on 2025-03-15 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_app', '0006_quizsubmission_learner'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizsubmission',
            name='score',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
