# Generated by Django 5.1.6 on 2025-03-15 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_app', '0007_quizsubmission_score'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quizsubmission',
            name='learner',
        ),
        migrations.RemoveField(
            model_name='quizsubmission',
            name='score',
        ),
    ]
